// <auto-generated />
using System;
using ControlDespachos.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ControlDespachos.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ControlDespachos.Core.Entities.AdjuntoGuia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("GuiaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlStorage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GuiaId");

                    b.ToTable("adjuntos_guias", (string)null);
                });

            modelBuilder.Entity("ControlDespachos.Core.Entities.CierreGuia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DocumentosEntregados")
                        .HasColumnType("bit");

                    b.Property<string>("EstadoEntrega")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("GuiaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeSpan>("HoraFin")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("time");

                    b.Property<decimal?>("KmFin")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("KmInicio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GuiaId");

                    b.ToTable("cierre_guias", (string)null);
                });

            modelBuilder.Entity("ControlDespachos.Core.Entities.CierreHojaRuta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("HojaRutaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeSpan>("HoraCierre")
                        .HasColumnType("time");

                    b.Property<decimal?>("KmTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ObservacionesFinales")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HojaRutaId");

                    b.ToTable("cierre_hoja_ruta", (string)null);
                });

            modelBuilder.Entity("ControlDespachos.Core.Entities.GuiaRemision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CantidadEmitida")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("EmitidaPor")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EstadoGre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("HoraEmision")
                        .HasColumnType("time");

                    b.Property<string>("NumeroGre")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid?>("OvId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Programada")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("EmitidaPor");

                    b.HasIndex("NumeroGre")
                        .IsUnique();

                    b.HasIndex("OvId");

                    b.ToTable("guias_remision", (string)null);
                });

            modelBuilder.Entity("ControlDespachos.Core.Entities.HojaRuta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Chofer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("Turno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("hojas_ruta", (string)null);
                });

            modelBuilder.Entity("ControlDespachos.Core.Entities.HojaRutaGuia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("GuiaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("HojaRutaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("GuiaId");

                    b.HasIndex("HojaRutaId", "GuiaId")
                        .IsUnique()
                        .HasFilter("[HojaRutaId] IS NOT NULL AND [GuiaId] IS NOT NULL");

                    b.ToTable("hoja_ruta_guias", (string)null);
                });

            modelBuilder.Entity("ControlDespachos.Core.Entities.Nota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<string>("OvId")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("OvNum")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("notas", (string)null);
                });

            modelBuilder.Entity("ControlDespachos.Core.Entities.NotaImagen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Base64Data")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NotaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NotaId");

                    b.ToTable("nota_imagenes", (string)null);
                });

            modelBuilder.Entity("ControlDespachos.Core.Entities.OrdenVenta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AlmacenOrigen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AreaSolicitante")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("ClienteId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClienteNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CourierSugerido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Distrito")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DomicilioDestino")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaNecesidad")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("HoraCreacion")
                        .HasColumnType("time");

                    b.Property<string>("LineaProductiva")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroOt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroOv")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("OcCotizacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PiezaCodigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PiezaDescripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SolicitadoPor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Udm")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("NumeroOv")
                        .IsUnique();

                    b.ToTable("ordenes_venta", (string)null);
                });

            modelBuilder.Entity("ControlDespachos.Core.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("ControlDespachos.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid?>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("ControlDespachos.Core.Entities.AdjuntoGuia", b =>
                {
                    b.HasOne("ControlDespachos.Core.Entities.GuiaRemision", "GuiaRemision")
                        .WithMany()
                        .HasForeignKey("GuiaId");

                    b.Navigation("GuiaRemision");
                });

            modelBuilder.Entity("ControlDespachos.Core.Entities.CierreGuia", b =>
                {
                    b.HasOne("ControlDespachos.Core.Entities.GuiaRemision", "GuiaRemision")
                        .WithMany()
                        .HasForeignKey("GuiaId");

                    b.Navigation("GuiaRemision");
                });

            modelBuilder.Entity("ControlDespachos.Core.Entities.CierreHojaRuta", b =>
                {
                    b.HasOne("ControlDespachos.Core.Entities.HojaRuta", "HojaRuta")
                        .WithMany()
                        .HasForeignKey("HojaRutaId");

                    b.Navigation("HojaRuta");
                });

            modelBuilder.Entity("ControlDespachos.Core.Entities.GuiaRemision", b =>
                {
                    b.HasOne("ControlDespachos.Core.Entities.User", "EmitidaPorUser")
                        .WithMany()
                        .HasForeignKey("EmitidaPor");

                    b.HasOne("ControlDespachos.Core.Entities.OrdenVenta", "OrdenVenta")
                        .WithMany()
                        .HasForeignKey("OvId");

                    b.Navigation("EmitidaPorUser");

                    b.Navigation("OrdenVenta");
                });

            modelBuilder.Entity("ControlDespachos.Core.Entities.HojaRutaGuia", b =>
                {
                    b.HasOne("ControlDespachos.Core.Entities.GuiaRemision", "GuiaRemision")
                        .WithMany()
                        .HasForeignKey("GuiaId");

                    b.HasOne("ControlDespachos.Core.Entities.HojaRuta", "HojaRuta")
                        .WithMany("Guias")
                        .HasForeignKey("HojaRutaId");

                    b.Navigation("GuiaRemision");

                    b.Navigation("HojaRuta");
                });

            modelBuilder.Entity("ControlDespachos.Core.Entities.NotaImagen", b =>
                {
                    b.HasOne("ControlDespachos.Core.Entities.Nota", "Nota")
                        .WithMany("Imagenes")
                        .HasForeignKey("NotaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nota");
                });

            modelBuilder.Entity("ControlDespachos.Core.Entities.User", b =>
                {
                    b.HasOne("ControlDespachos.Core.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ControlDespachos.Core.Entities.HojaRuta", b =>
                {
                    b.Navigation("Guias");
                });

            modelBuilder.Entity("ControlDespachos.Core.Entities.Nota", b =>
                {
                    b.Navigation("Imagenes");
                });

            modelBuilder.Entity("ControlDespachos.Core.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
